export const SHIPMENT_COUNT_REQUEST = 'SHIPMENT_COUNT_REQUEST';
export const SHIPMENT_COUNT_SUCCESS = 'SHIPMENT_COUNT_SUCCESS';
export const SHIPMENT_COUNT_FAILURE = 'SHIPMENT_COUNT_FAILURE';


export const SHIPMENT_HISTORY_REQUEST = 'SHIPMENT_HISTORY_REQUEST';
export const SHIPMENT_HISTORY_SUCCESS = 'SHIPMENT_HISTORY_SUCCESS';
export const SHIPMENT_HISTORY_FAILURE = 'SHIPMENT_HISTORY_FAILURE';

export const INBOX_COUNT_REQUEST = 'INBOX_COUNT_REQUEST';
export const INBOX_COUNT_SUCCESS = 'INBOX_COUNT_SUCCESS';
export const INBOX_COUNT_FAILURE = 'INBOX_COUNT_FAILURE';

export const SAILING_REQUEST = 'SAILING_REQUEST';
export const SAILING_SUCCESS = 'SAILING_SUCCESS';
export const SAILING_FAILURE = 'SAILING_FAILURE';

export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_SUCCESS = 'TODO_SUCCESS';
export const TODO_FAILURE = 'TODO_FAILURE';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';

export const PORT_REQUEST = 'PORT_REQUEST';
export const PORT_SUCCESS = 'PORT_SUCCESS';
export const PORT_FAILURE = 'PORT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const OPENSAILING_REQUEST = 'OPENSAILING_REQUEST';
export const OPENSAILING_SUCCESS = 'OPENSAILING_SUCCESS';
export const OPENSAILING_FAILURE = 'OPENSAILING_FAILURE';

export const MAP_REQUEST = 'MAP_REQUEST';
export const MAP_SUCCESS = 'MAP_SUCCESS';
export const MAP_FAILURE = 'MAP_FAILURE';

