export const currencies = [
  {
    entity: "BARBADOS",
    currency: "Barbados Dollar",
    label: "BBD",
    value: "BBD",
    numericcode: "052",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CHAD",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "COCOS (KEELING) ISLANDS (THE)",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "EL SALVADOR",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LUXEMBOURG",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "POLAND",
    currency: "Zloty",
    label: "PLN",
    value: "PLN",
    numericcode: "985",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PUERTO RICO",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAO TOME AND PRINCIPE",
    currency: "Dobra",
    label: "STN",
    value: "STN",
    numericcode: "930",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SVALBARD AND JAN MAYEN",
    currency: "Norwegian Krone",
    label: "NOK",
    value: "NOK",
    numericcode: "578",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ01_Bond Markets Unit European_EURCO",
    currency: "Bond Markets Unit European Composite Unit (EURCO)",
    label: "XBA",
    value: "XBA",
    numericcode: "955",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "ZZ02_Bond Markets Unit European_EMU-6",
    currency: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    label: "XBB",
    value: "XBB",
    numericcode: "956",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "ANDORRA",
    currency: "Andorran Peseta",
    label: "ADP",
    value: "ADP",
    numericcode: "020",
    minorunit: null,
    withdrawaldate: "2003-07",
  },
  {
    entity: "GUINEA-BISSAU",
    currency: "Guinea-Bissau Peso",
    label: "GWP",
    value: "GWP",
    numericcode: "624",
    minorunit: null,
    withdrawaldate: "1997-05",
  },
  {
    entity: "HOLY SEE (VATICAN CITY STATE)",
    currency: "Italian Lira",
    label: "ITL",
    value: "ITL",
    numericcode: "380",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "IRELAND",
    currency: "Irish Pound",
    label: "IEP",
    value: "IEP",
    numericcode: "372",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "ISRAEL",
    currency: "Old Shekel",
    label: "ILR",
    value: "ILR",
    numericcode: "376",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "LUXEMBOURG",
    currency: "Luxembourg Convertible Franc",
    label: "LUC",
    value: "LUC",
    numericcode: "989",
    minorunit: null,
    withdrawaldate: "1990-03",
  },
  {
    entity: "LUXEMBOURG",
    currency: "Luxembourg Financial Franc",
    label: "LUL",
    value: "LUL",
    numericcode: "988",
    minorunit: null,
    withdrawaldate: "1990-03",
  },
  {
    entity: "ROMANIA",
    currency: "Old Leu",
    label: "ROL",
    value: "ROL",
    numericcode: "642",
    minorunit: null,
    withdrawaldate: "2005-06",
  },
  {
    entity: "TAJIKISTAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1995-05",
  },
  {
    entity: "VENEZUELA",
    currency: "Bolivar Fuerte",
    label: "VEF",
    value: "VEF",
    numericcode: "937",
    minorunit: null,
    withdrawaldate: "2011-12",
  },
  {
    entity: "ZIMBABWE",
    currency: "Zimbabwe Dollar (new)",
    label: "ZWN",
    value: "ZWN",
    numericcode: "942",
    minorunit: null,
    withdrawaldate: "2006-09",
  },
  {
    entity: "AUSTRIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "DENMARK",
    currency: "Danish Krone",
    label: "DKK",
    value: "DKK",
    numericcode: "208",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ITALY",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PERU",
    currency: "Sol",
    label: "PEN",
    value: "PEN",
    numericcode: "604",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "R\u00c9UNION",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT KITTS AND NEVIS",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
    currency: "Sucre",
    label: "XSU",
    value: "XSU",
    numericcode: "994",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "TUNISIA",
    currency: "Tunisian Dinar",
    label: "TND",
    value: "TND",
    numericcode: "788",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "VANUATU",
    currency: "Vatu",
    label: "VUV",
    value: "VUV",
    numericcode: "548",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "PERU",
    currency: "Inti",
    label: "PEI",
    value: "PEI",
    numericcode: "604",
    minorunit: null,
    withdrawaldate: "1991-07",
  },
  {
    entity: "POLAND",
    currency: "Zloty",
    label: "PLZ",
    value: "PLZ",
    numericcode: "616",
    minorunit: null,
    withdrawaldate: "1997-01",
  },
  {
    entity: "SPAIN",
    currency: "Spanish Peseta",
    label: "ESA",
    value: "ESA",
    numericcode: "996",
    minorunit: null,
    withdrawaldate: "1978 to 1981",
  },
  {
    entity: "\u00c5LAND ISLANDS",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ANTARCTICA",
    currency: "No universal currency",
    label: null,
    value: "nul",
    numericcode: null,
    minorunit: null,
    withdrawaldate: null,
  },
  {
    entity: "BOLIVIA (PLURINATIONAL STATE OF)",
    currency: "Boliviano",
    label: "BOB",
    value: "BOB",
    numericcode: "068",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FRENCH SOUTHERN TERRITORIES (THE)",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GUERNSEY",
    currency: "Pound Sterling",
    label: "GBP",
    value: "GBP",
    numericcode: "826",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    currency: "North Korean Won",
    label: "KPW",
    value: "KPW",
    numericcode: "408",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LITHUANIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MADAGASCAR",
    currency: "Malagasy Ariary",
    label: "MGA",
    value: "MGA",
    numericcode: "969",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "OMAN",
    currency: "Rial Omani",
    label: "OMR",
    value: "OMR",
    numericcode: "512",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "RWANDA",
    currency: "Rwanda Franc",
    label: "RWF",
    value: "RWF",
    numericcode: "646",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "SAN MARINO",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SIERRA LEONE",
    currency: "Leone",
    label: "SLL",
    value: "SLL",
    numericcode: "694",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SINGAPORE",
    currency: "Singapore Dollar",
    label: "SGD",
    value: "SGD",
    numericcode: "702",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TIMOR-LESTE",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "WALLIS AND FUTUNA",
    currency: "CFP Franc",
    label: "XPF",
    value: "XPF",
    numericcode: "953",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "ROMANIA",
    currency: "New Romanian Leu",
    label: "RON",
    value: "RON",
    numericcode: "946",
    minorunit: null,
    withdrawaldate: "2015-06",
  },
  {
    entity: "SOUTH AFRICA",
    currency: "Financial Rand",
    label: "ZAL",
    value: "ZAL",
    numericcode: "991",
    minorunit: null,
    withdrawaldate: "1995-03",
  },
  {
    entity: "SPAIN",
    currency: "Spanish Peseta",
    label: "ESP",
    value: "ESP",
    numericcode: "724",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "VENEZUELA",
    currency: "Bolivar",
    label: "VEB",
    value: "VEB",
    numericcode: "862",
    minorunit: null,
    withdrawaldate: "2008-01",
  },
  {
    entity: "VIETNAM",
    currency: "Old Dong",
    label: "VNC",
    value: "VNC",
    numericcode: "704",
    minorunit: null,
    withdrawaldate: "1989-1990",
  },
  {
    entity: "BHUTAN",
    currency: "Ngultrum",
    label: "BTN",
    value: "BTN",
    numericcode: "064",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CHINA",
    currency: "Yuan Renminbi",
    label: "CNY",
    value: "CNY",
    numericcode: "156",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "EL SALVADOR",
    currency: "El Salvador Colon",
    label: "SVC",
    value: "SVC",
    numericcode: "222",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GREECE",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "HONG KONG",
    currency: "Hong Kong Dollar",
    label: "HKD",
    value: "HKD",
    numericcode: "344",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LESOTHO",
    currency: "Loti",
    label: "LSL",
    value: "LSL",
    numericcode: "426",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MAURITIUS",
    currency: "Mauritius Rupee",
    label: "MUR",
    value: "MUR",
    numericcode: "480",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NAMIBIA",
    currency: "Rand",
    label: "ZAR",
    value: "ZAR",
    numericcode: "710",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NIUE",
    currency: "New Zealand Dollar",
    label: "NZD",
    value: "NZD",
    numericcode: "554",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ08_Gold",
    currency: "Gold",
    label: "XAU",
    value: "XAU",
    numericcode: "959",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "CROATIA",
    currency: "Croatian Kuna",
    label: "HRK",
    value: "HRK",
    numericcode: "191",
    minorunit: null,
    withdrawaldate: "2015-06",
  },
  {
    entity: "LAO",
    currency: "Pathet Lao Kip",
    label: "LAJ",
    value: "LAJ",
    numericcode: "418",
    minorunit: null,
    withdrawaldate: "1979-12",
  },
  {
    entity: "UZBEKISTAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-07",
  },
  {
    entity: "BULGARIA",
    currency: "Bulgarian Lev",
    label: "BGN",
    value: "BGN",
    numericcode: "975",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "EUROPEAN UNION",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FAROE ISLANDS (THE)",
    currency: "Danish Krone",
    label: "DKK",
    value: "DKK",
    numericcode: "208",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GEORGIA",
    currency: "Lari",
    label: "GEL",
    value: "GEL",
    numericcode: "981",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GUAM",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "KENYA",
    currency: "Kenyan Shilling",
    label: "KES",
    value: "KES",
    numericcode: "404",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MONGOLIA",
    currency: "Tugrik",
    label: "MNT",
    value: "MNT",
    numericcode: "496",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    currency: "Saint Helena Pound",
    label: "SHP",
    value: "SHP",
    numericcode: "654",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UKRAINE",
    currency: "Hryvnia",
    label: "UAH",
    value: "UAH",
    numericcode: "980",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency: "Bol\u00edvar",
    label: "VEF",
    value: "VEF",
    numericcode: "937",
    minorunit: null,
    withdrawaldate: "2018-08",
  },
  {
    entity: "YUGOSLAVIA",
    currency: "New Yugoslavian Dinar",
    label: "YUD",
    value: "YUD",
    numericcode: "890",
    minorunit: null,
    withdrawaldate: "1990-01",
  },
  {
    entity: "BONAIRE, SINT EUSTATIUS AND SABA",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CAMEROON",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "DJIBOUTI",
    currency: "Djibouti Franc",
    label: "DJF",
    value: "DJF",
    numericcode: "262",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "GUATEMALA",
    currency: "Quetzal",
    label: "GTQ",
    value: "GTQ",
    numericcode: "320",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "IRELAND",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NETHERLANDS (THE)",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NORTHERN MARIANA ISLANDS (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PANAMA",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SINT MAARTEN (DUTCH PART)",
    currency: "Netherlands Antillean Guilder",
    label: "ANG",
    value: "ANG",
    numericcode: "532",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    currency: "No universal currency",
    label: null,
    value: "nul",
    numericcode: null,
    minorunit: null,
    withdrawaldate: null,
  },
  {
    entity: "TOKELAU",
    currency: "New Zealand Dollar",
    label: "NZD",
    value: "NZD",
    numericcode: "554",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BURMA",
    currency: "Kyat",
    label: "BUK",
    value: "BUK",
    numericcode: "104",
    minorunit: null,
    withdrawaldate: "1990-02",
  },
  {
    entity: "FRANCE",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "MEXICO",
    currency: "Mexican Peso",
    label: "MXP",
    value: "MXP",
    numericcode: "484",
    minorunit: null,
    withdrawaldate: "1993-01",
  },
  {
    entity: "NETHERLANDS",
    currency: "Netherlands Guilder",
    label: "NLG",
    value: "NLG",
    numericcode: "528",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "UGANDA",
    currency: "Old Shilling",
    label: "UGW",
    value: "UGW",
    numericcode: "800",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "YUGOSLAVIA",
    currency: "Yugoslavian Dinar",
    label: "YUN",
    value: "YUN",
    numericcode: "890",
    minorunit: null,
    withdrawaldate: "1995-11",
  },
  {
    entity: "BAHRAIN",
    currency: "Bahraini Dinar",
    label: "BHD",
    value: "BHD",
    numericcode: "048",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "CHILE",
    currency: "Unidad de Fomento",
    label: "CLF",
    value: "CLF",
    numericcode: "990",
    minorunit: "4",
    withdrawaldate: null,
  },
  {
    entity: "ERITREA",
    currency: "Nakfa",
    label: "ERN",
    value: "ERN",
    numericcode: "232",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FINLAND",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GUYANA",
    currency: "Guyana Dollar",
    label: "GYD",
    value: "GYD",
    numericcode: "328",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MALTA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NORFOLK ISLAND",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NORWAY",
    currency: "Norwegian Krone",
    label: "NOK",
    value: "NOK",
    numericcode: "578",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PANAMA",
    currency: "Balboa",
    label: "PAB",
    value: "PAB",
    numericcode: "590",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SENEGAL",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "ZZ06_Testing_Code",
    currency: "Codes specifically reserved for testing purposes",
    label: "XTS",
    value: "XTS",
    numericcode: "963",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "ARGENTINA",
    currency: "Peso Argentino",
    label: "ARP",
    value: "ARP",
    numericcode: "032",
    minorunit: null,
    withdrawaldate: "1985-07",
  },
  {
    entity: "FRENCH GUIANA",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "LITHUANIA",
    currency: "Talonas",
    label: "LTT",
    value: "LTT",
    numericcode: "440",
    minorunit: null,
    withdrawaldate: "1993-07",
  },
  {
    entity: "MOZAMBIQUE",
    currency: "Mozambique Metical",
    label: "MZM",
    value: "MZM",
    numericcode: "508",
    minorunit: null,
    withdrawaldate: "2006-06",
  },
  {
    entity: "PORTUGAL",
    currency: "Portuguese Escudo",
    label: "PTE",
    value: "PTE",
    numericcode: "620",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "SERBIA AND MONTENEGRO",
    currency: "Serbian Dinar",
    label: "CSD",
    value: "CSD",
    numericcode: "891",
    minorunit: null,
    withdrawaldate: "2006-10",
  },
  {
    entity: "ZAMBIA",
    currency: "Zambian Kwacha",
    label: "ZMK",
    value: "ZMK",
    numericcode: "894",
    minorunit: null,
    withdrawaldate: "2012-12",
  },
  {
    entity: "BELIZE",
    currency: "Belize Dollar",
    label: "BZD",
    value: "BZD",
    numericcode: "084",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CYPRUS",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FALKLAND ISLANDS (THE) [MALVINAS]",
    currency: "Falkland Islands Pound",
    label: "FKP",
    value: "FKP",
    numericcode: "238",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MEXICO",
    currency: "Mexican Unidad de Inversion (UDI)",
    label: "MXV",
    value: "MXV",
    numericcode: "979",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PALESTINE, STATE OF",
    currency: "No universal currency",
    label: null,
    value: "nul",
    numericcode: null,
    minorunit: null,
    withdrawaldate: null,
  },
  {
    entity: "SOLOMON ISLANDS",
    currency: "Solomon Islands Dollar",
    label: "SBD",
    value: "SBD",
    numericcode: "090",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SWITZERLAND",
    currency: "WIR Franc",
    label: "CHW",
    value: "CHW",
    numericcode: "948",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TAIWAN (PROVINCE OF CHINA)",
    currency: "New Taiwan Dollar",
    label: "TWD",
    value: "TWD",
    numericcode: "901",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TRINIDAD AND TOBAGO",
    currency: "Trinidad and Tobago Dollar",
    label: "TTD",
    value: "TTD",
    numericcode: "780",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TURKEY",
    currency: "Turkish Lira",
    label: "TRY",
    value: "TRY",
    numericcode: "949",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "URUGUAY",
    currency: "Peso Uruguayo",
    label: "UYU",
    value: "UYU",
    numericcode: "858",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ANDORRA",
    currency: "Spanish Peseta",
    label: "ESP",
    value: "ESP",
    numericcode: "724",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "BELGIUM",
    currency: "Convertible Franc",
    label: "BEC",
    value: "BEC",
    numericcode: "993",
    minorunit: null,
    withdrawaldate: "1990-03",
  },
  {
    entity: "BELGIUM",
    currency: "Financial Franc",
    label: "BEL",
    value: "BEL",
    numericcode: "992",
    minorunit: null,
    withdrawaldate: "1990-03",
  },
  {
    entity: "GEORGIA",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-04",
  },
  {
    entity: "GREECE",
    currency: "Drachma",
    label: "GRD",
    value: "GRD",
    numericcode: "300",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "PERU",
    currency: "Nuevo Sol",
    label: "PEN",
    value: "PEN",
    numericcode: "604",
    minorunit: null,
    withdrawaldate: "2015-12",
  },
  {
    entity: "TIMOR-LESTE",
    currency: "Rupiah",
    label: "IDR",
    value: "IDR",
    numericcode: "360",
    minorunit: null,
    withdrawaldate: "2002-07",
  },
  {
    entity: "ZAIRE",
    currency: "Zaire",
    label: "ZRZ",
    value: "ZRZ",
    numericcode: "180",
    minorunit: null,
    withdrawaldate: "1994-02",
  },
  {
    entity: "ANDORRA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BELARUS",
    currency: "Belarusian Ruble",
    label: "BYN",
    value: "BYN",
    numericcode: "933",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ICELAND",
    currency: "Iceland Krona",
    label: "ISK",
    value: "ISK",
    numericcode: "352",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "LIBERIA",
    currency: "Liberian Dollar",
    label: "LRD",
    value: "LRD",
    numericcode: "430",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MARTINIQUE",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT LUCIA",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
    currency: "Pound Sterling",
    label: "GBP",
    value: "GBP",
    numericcode: "826",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ARGENTINA",
    currency: "Austral",
    label: "ARA",
    value: "ARA",
    numericcode: "032",
    minorunit: null,
    withdrawaldate: "1992-01",
  },
  {
    entity: "GERMAN DEMOCRATIC REPUBLIC",
    currency: "Mark der DDR",
    label: "DDM",
    value: "DDM",
    numericcode: "278",
    minorunit: null,
    withdrawaldate: "1990-07 to 1990-09",
  },
  {
    entity: "GHANA",
    currency: "Cedi",
    label: "GHC",
    value: "GHC",
    numericcode: "288",
    minorunit: null,
    withdrawaldate: "2008-01",
  },
  {
    entity: "MOLDOVA, REPUBLIC OF",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1993-12",
  },
  {
    entity: "NETHERLANDS ANTILLES",
    currency: "Netherlands Antillean Guilder",
    label: "ANG",
    value: "ANG",
    numericcode: "532",
    minorunit: null,
    withdrawaldate: "2010-10",
  },
  {
    entity: "SUDAN",
    currency: "Sudanese Pound",
    label: "SDP",
    value: "SDP",
    numericcode: "736",
    minorunit: null,
    withdrawaldate: "1998-06",
  },
  {
    entity: "UKRAINE",
    currency: "Karbovanet",
    label: "UAK",
    value: "UAK",
    numericcode: "804",
    minorunit: null,
    withdrawaldate: "1996-09",
  },
  {
    entity: "BAHAMAS (THE)",
    currency: "Bahamian Dollar",
    label: "BSD",
    value: "BSD",
    numericcode: "044",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BURKINA FASO",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "GABON",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "HEARD ISLAND AND McDONALD ISLANDS",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "INDONESIA",
    currency: "Rupiah",
    label: "IDR",
    value: "IDR",
    numericcode: "360",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    currency: "Lao Kip",
    label: "LAK",
    value: "LAK",
    numericcode: "418",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MARSHALL ISLANDS (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MOLDOVA (THE REPUBLIC OF)",
    currency: "Moldovan Leu",
    label: "MDL",
    value: "MDL",
    numericcode: "498",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MOZAMBIQUE",
    currency: "Mozambique Metical",
    label: "MZN",
    value: "MZN",
    numericcode: "943",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SOUTH SUDAN",
    currency: "South Sudanese Pound",
    label: "SSP",
    value: "SSP",
    numericcode: "728",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "URUGUAY",
    currency: "Uruguay Peso en Unidades Indexadas (UI)",
    label: "UYI",
    value: "UYI",
    numericcode: "940",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "ARMENIA",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-08",
  },
  {
    entity: "BELARUS",
    currency: "Belarusian Ruble",
    label: "BYR",
    value: "BYR",
    numericcode: "974",
    minorunit: null,
    withdrawaldate: "2017-01",
  },
  {
    entity: "CZECHOSLOVAKIA",
    currency: "Krona A/53",
    label: "CSJ",
    value: "CSJ",
    numericcode: "203",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "GUINEA-BISSAU",
    currency: "Guinea Escudo",
    label: "GWE",
    value: "GWE",
    numericcode: "624",
    minorunit: null,
    withdrawaldate: "1978 to 1981",
  },
  {
    entity: "LUXEMBOURG",
    currency: "Luxembourg Franc",
    label: "LUF",
    value: "LUF",
    numericcode: "442",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "HAITI",
    currency: "Gourde",
    label: "HTG",
    value: "HTG",
    numericcode: "332",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "KOREA (THE REPUBLIC OF)",
    currency: "Won",
    label: "KRW",
    value: "KRW",
    numericcode: "410",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "MAYOTTE",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PORTUGAL",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "QATAR",
    currency: "Qatari Rial",
    label: "QAR",
    value: "QAR",
    numericcode: "634",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "VIRGIN ISLANDS (U.S.)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FRENCH SOUTHERN TERRITORIES",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "NICARAGUA",
    currency: "Cordoba",
    label: "NIC",
    value: "NIC",
    numericcode: "558",
    minorunit: null,
    withdrawaldate: "1990-10",
  },
  {
    entity: "SLOVENIA",
    currency: "Tolar",
    label: "SIT",
    value: "SIT",
    numericcode: "705",
    minorunit: null,
    withdrawaldate: "2007-01",
  },
  {
    entity: "SOUTH SUDAN",
    currency: "Sudanese Pound",
    label: "SDG",
    value: "SDG",
    numericcode: "938",
    minorunit: null,
    withdrawaldate: "2012-09",
  },
  {
    entity: "SWITZERLAND",
    currency: "WIR Franc (for electronic)",
    label: "CHC",
    value: "CHC",
    numericcode: "948",
    minorunit: null,
    withdrawaldate: "2004-11",
  },
  {
    entity: "ANGOLA",
    currency: "Kwanza",
    label: "AOA",
    value: "AOA",
    numericcode: "973",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BRITISH INDIAN OCEAN TERRITORY (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PHILIPPINES (THE)",
    currency: "Philippine Peso",
    label: "PHP",
    value: "PHP",
    numericcode: "608",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAMOA",
    currency: "Tala",
    label: "WST",
    value: "WST",
    numericcode: "882",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BOSNIA AND HERZEGOVINA",
    currency: "Dinar",
    label: "BAD",
    value: "BAD",
    numericcode: "070",
    minorunit: null,
    withdrawaldate: "1998-07",
  },
  {
    entity: "BRAZIL",
    currency: "New Cruzado",
    label: "BRN",
    value: "BRN",
    numericcode: "076",
    minorunit: null,
    withdrawaldate: "1990-03",
  },
  {
    entity: "BRAZIL",
    currency: "Cruzeiro Real",
    label: "BRR",
    value: "BRR",
    numericcode: "987",
    minorunit: null,
    withdrawaldate: "1994-07",
  },
  {
    entity: "CYPRUS",
    currency: "Cyprus Pound",
    label: "CYP",
    value: "CYP",
    numericcode: "196",
    minorunit: null,
    withdrawaldate: "2008-01",
  },
  {
    entity: "GUINEA",
    currency: "Syli",
    label: "GNS",
    value: "GNS",
    numericcode: "324",
    minorunit: null,
    withdrawaldate: "1986-02",
  },
  {
    entity: "KAZAKHSTAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-05",
  },
  {
    entity: "LITHUANIA",
    currency: "Lithuanian Litas",
    label: "LTL",
    value: "LTL",
    numericcode: "440",
    minorunit: null,
    withdrawaldate: "2014-12",
  },
  {
    entity: "MALTA",
    currency: "Maltese Pound",
    label: "MTP",
    value: "MTP",
    numericcode: "470",
    minorunit: null,
    withdrawaldate: "1983-06",
  },
  {
    entity: "TURKMENISTAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1993-10",
  },
  {
    entity: "URUGUAY",
    currency: "Old Uruguay Peso",
    label: "UYN",
    value: "UYN",
    numericcode: "858",
    minorunit: null,
    withdrawaldate: "1989-12",
  },
  {
    entity: "ALGERIA",
    currency: "Algerian Dinar",
    label: "DZD",
    value: "DZD",
    numericcode: "012",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ARUBA",
    currency: "Aruban Florin",
    label: "AWG",
    value: "AWG",
    numericcode: "533",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CANADA",
    currency: "Canadian Dollar",
    label: "CAD",
    value: "CAD",
    numericcode: "124",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CAYMAN ISLANDS (THE)",
    currency: "Cayman Islands Dollar",
    label: "KYD",
    value: "KYD",
    numericcode: "136",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "EQUATORIAL GUINEA",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "GREENLAND",
    currency: "Danish Krone",
    label: "DKK",
    value: "DKK",
    numericcode: "208",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SPAIN",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SYRIAN ARAB REPUBLIC",
    currency: "Syrian Pound",
    label: "SYP",
    value: "SYP",
    numericcode: "760",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TANZANIA, UNITED REPUBLIC OF",
    currency: "Tanzanian Shilling",
    label: "TZS",
    value: "TZS",
    numericcode: "834",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "\u00c5LAND ISLANDS",
    currency: "Markka",
    label: "FIM",
    value: "FIM",
    numericcode: "246",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "KYRGYZSTAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1993-01",
  },
  {
    entity: "MALDIVES",
    currency: "Maldive Rupee",
    label: "MVQ",
    value: "MVQ",
    numericcode: "462",
    minorunit: null,
    withdrawaldate: "1989-12",
  },
  {
    entity: "UNION OF SOVIET SOCIALIST REPUBLICS",
    currency: "Rouble",
    label: "SUR",
    value: "SUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1990-12",
  },
  {
    entity: "UNITED STATES",
    currency: "US Dollar (Same day)",
    label: "USS",
    value: "USS",
    numericcode: "998",
    minorunit: null,
    withdrawaldate: "2014-03",
  },
  {
    entity: "ZAIRE",
    currency: "New Zaire",
    label: "ZRN",
    value: "ZRN",
    numericcode: "180",
    minorunit: null,
    withdrawaldate: "1999-06",
  },
  {
    entity: "ANGUILLA",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CAMBODIA",
    currency: "Riel",
    label: "KHR",
    value: "KHR",
    numericcode: "116",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "COOK ISLANDS (THE)",
    currency: "New Zealand Dollar",
    label: "NZD",
    value: "NZD",
    numericcode: "554",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "COSTA RICA",
    currency: "Costa Rican Colon",
    label: "CRC",
    value: "CRC",
    numericcode: "188",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ECUADOR",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "HAITI",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "INDIA",
    currency: "Indian Rupee",
    label: "INR",
    value: "INR",
    numericcode: "356",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MONTENEGRO",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NEW CALEDONIA",
    currency: "CFP Franc",
    label: "XPF",
    value: "XPF",
    numericcode: "953",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "NICARAGUA",
    currency: "Cordoba Oro",
    label: "NIO",
    value: "NIO",
    numericcode: "558",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT PIERRE AND MIQUELON",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SRI LANKA",
    currency: "Sri Lanka Rupee",
    label: "LKR",
    value: "LKR",
    numericcode: "144",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SURINAME",
    currency: "Surinam Dollar",
    label: "SRD",
    value: "SRD",
    numericcode: "968",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TURKS AND CAICOS ISLANDS (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "URUGUAY",
    currency: "Unidad Previsional",
    label: "UYW",
    value: "UYW",
    numericcode: "927",
    minorunit: "4",
    withdrawaldate: null,
  },
  {
    entity: "VIRGIN ISLANDS (BRITISH)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ11_Silver",
    currency: "Silver",
    label: "XAG",
    value: "XAG",
    numericcode: "961",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "GERMANY",
    currency: "Deutsche Mark",
    label: "DEM",
    value: "DEM",
    numericcode: "276",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "LESOTHO",
    currency: "Financial Rand",
    label: "ZAL",
    value: "ZAL",
    numericcode: "991",
    minorunit: null,
    withdrawaldate: "1995-03",
  },
  {
    entity: "ZZ05_UIC-Franc",
    currency: "UIC-Franc",
    label: "XFU",
    value: "XFU",
    numericcode: null,
    minorunit: null,
    withdrawaldate: "2013-11",
  },
  {
    entity: "BENIN",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "CABO VERDE",
    currency: "Cabo Verde Escudo",
    label: "CVE",
    value: "CVE",
    numericcode: "132",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CENTRAL AFRICAN REPUBLIC (THE)",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "CHILE",
    currency: "Chilean Peso",
    label: "CLP",
    value: "CLP",
    numericcode: "152",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
    currency: "Congolese Franc",
    label: "CDF",
    value: "CDF",
    numericcode: "976",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CONGO (THE)",
    currency: "CFA Franc BEAC",
    label: "XAF",
    value: "XAF",
    numericcode: "950",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "CUBA",
    currency: "Peso Convertible",
    label: "CUC",
    value: "CUC",
    numericcode: "931",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SWITZERLAND",
    currency: "WIR Euro",
    label: "CHE",
    value: "CHE",
    numericcode: "947",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ04_Bond Markets Unit European_EUA-17",
    currency: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    label: "XBD",
    value: "XBD",
    numericcode: "958",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "ALBANIA",
    currency: "Old Lek",
    label: "ALK",
    value: "ALK",
    numericcode: "008",
    minorunit: null,
    withdrawaldate: "1989-12",
  },
  {
    entity: "BULGARIA",
    currency: "Lev A/62",
    label: "BGK",
    value: "BGK",
    numericcode: "100",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "ESTONIA",
    currency: "Kroon",
    label: "EEK",
    value: "EEK",
    numericcode: "233",
    minorunit: null,
    withdrawaldate: "2011-01",
  },
  {
    entity: "GEORGIA",
    currency: "Georgian Coupon",
    label: "GEK",
    value: "GEK",
    numericcode: "268",
    minorunit: null,
    withdrawaldate: "1995-10",
  },
  {
    entity: "LATVIA",
    currency: "Latvian Ruble",
    label: "LVR",
    value: "LVR",
    numericcode: "428",
    minorunit: null,
    withdrawaldate: "1994-12",
  },
  {
    entity: "TURKEY",
    currency: "Old Turkish Lira",
    label: "TRL",
    value: "TRL",
    numericcode: "792",
    minorunit: null,
    withdrawaldate: "2005-12",
  },
  {
    entity: "AZERBAIJAN",
    currency: "Azerbaijan Manat",
    label: "AZN",
    value: "AZN",
    numericcode: "944",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CZECHIA",
    currency: "Czech Koruna",
    label: "CZK",
    value: "CZK",
    numericcode: "203",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UGANDA",
    currency: "Uganda Shilling",
    label: "UGX",
    value: "UGX",
    numericcode: "800",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "UNITED STATES OF AMERICA (THE)",
    currency: "US Dollar (Next day)",
    label: "USN",
    value: "USN",
    numericcode: "997",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ10_Platinum",
    currency: "Platinum",
    label: "XPT",
    value: "XPT",
    numericcode: "962",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "BRAZIL",
    currency: "Cruzeiro",
    label: "BRB",
    value: "BRB",
    numericcode: "076",
    minorunit: null,
    withdrawaldate: "1986-03",
  },
  {
    entity: "BULGARIA",
    currency: "Lev",
    label: "BGL",
    value: "BGL",
    numericcode: "100",
    minorunit: null,
    withdrawaldate: "2003-11",
  },
  {
    entity: "LESOTHO",
    currency: "Loti",
    label: "LSM",
    value: "LSM",
    numericcode: "426",
    minorunit: null,
    withdrawaldate: "1985-05",
  },
  {
    entity: "PERU",
    currency: "Sol",
    label: "PEH",
    value: "PEH",
    numericcode: "604",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "URUGUAY",
    currency: "Uruguayan Peso",
    label: "UYP",
    value: "UYP",
    numericcode: "858",
    minorunit: null,
    withdrawaldate: "1993-03",
  },
  {
    entity: "ZZ02_RINET Funds Code",
    currency: "RINET Funds Code",
    label: "XRE",
    value: "XRE",
    numericcode: null,
    minorunit: null,
    withdrawaldate: "1999-11",
  },
  {
    entity: "BERMUDA",
    currency: "Bermudian Dollar",
    label: "BMD",
    value: "BMD",
    numericcode: "060",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BOLIVIA (PLURINATIONAL STATE OF)",
    currency: "Mvdol",
    label: "BOV",
    value: "BOV",
    numericcode: "984",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BOTSWANA",
    currency: "Pula",
    label: "BWP",
    value: "BWP",
    numericcode: "072",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BURUNDI",
    currency: "Burundi Franc",
    label: "BIF",
    value: "BIF",
    numericcode: "108",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "DOMINICAN REPUBLIC (THE)",
    currency: "Dominican Peso",
    label: "DOP",
    value: "DOP",
    numericcode: "214",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FRENCH POLYNESIA",
    currency: "CFP Franc",
    label: "XPF",
    value: "XPF",
    numericcode: "953",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "GUINEA-BISSAU",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "KAZAKHSTAN",
    currency: "Tenge",
    label: "KZT",
    value: "KZT",
    numericcode: "398",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SERBIA",
    currency: "Serbian Dinar",
    label: "RSD",
    value: "RSD",
    numericcode: "941",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZAMBIA",
    currency: "Zambian Kwacha",
    label: "ZMW",
    value: "ZMW",
    numericcode: "967",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BELGIUM",
    currency: "Belgian Franc",
    label: "BEF",
    value: "BEF",
    numericcode: "056",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "BRAZIL",
    currency: "Cruzado",
    label: "BRC",
    value: "BRC",
    numericcode: "076",
    minorunit: null,
    withdrawaldate: "1989-02",
  },
  {
    entity: "CZECHOSLOVAKIA",
    currency: "Koruna",
    label: "CSK",
    value: "CSK",
    numericcode: "200",
    minorunit: null,
    withdrawaldate: "1993-03",
  },
  {
    entity: "EQUATORIAL GUINEA",
    currency: "Ekwele",
    label: "GQE",
    value: "GQE",
    numericcode: "226",
    minorunit: null,
    withdrawaldate: "1986-06",
  },
  {
    entity: "GHANA",
    currency: "Ghana Cedi",
    label: "GHP",
    value: "GHP",
    numericcode: "939",
    minorunit: null,
    withdrawaldate: "2007-06",
  },
  {
    entity: "ICELAND",
    currency: "Old Krona",
    label: "ISJ",
    value: "ISJ",
    numericcode: "352",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "LATVIA",
    currency: "Latvian Lats",
    label: "LVL",
    value: "LVL",
    numericcode: "428",
    minorunit: null,
    withdrawaldate: "2014-01",
  },
  {
    entity: "RUSSIAN FEDERATION",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "2004-01",
  },
  {
    entity: "SERBIA AND MONTENEGRO",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: null,
    withdrawaldate: "2006-10",
  },
  {
    entity: "TIMOR-LESTE",
    currency: "Timor Escudo",
    label: "TPE",
    value: "TPE",
    numericcode: "626",
    minorunit: null,
    withdrawaldate: "2002-11",
  },
  {
    entity: "UGANDA",
    currency: "Uganda Shilling",
    label: "UGS",
    value: "UGS",
    numericcode: "800",
    minorunit: null,
    withdrawaldate: "1987-05",
  },
  {
    entity: "ZZ01_Gold-Franc",
    currency: "Gold-Franc",
    label: "XFO",
    value: "XFO",
    numericcode: null,
    minorunit: null,
    withdrawaldate: "2006-10",
  },
  {
    entity: "DOMINICA",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MALDIVES",
    currency: "Rufiyaa",
    label: "MVR",
    value: "MVR",
    numericcode: "462",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NEW ZEALAND",
    currency: "New Zealand Dollar",
    label: "NZD",
    value: "NZD",
    numericcode: "554",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PAPUA NEW GUINEA",
    currency: "Kina",
    label: "PGK",
    value: "PGK",
    numericcode: "598",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PITCAIRN",
    currency: "New Zealand Dollar",
    label: "NZD",
    value: "NZD",
    numericcode: "554",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UNITED ARAB EMIRATES (THE)",
    currency: "UAE Dirham",
    label: "AED",
    value: "AED",
    numericcode: "784",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UZBEKISTAN",
    currency: "Uzbekistan Sum",
    label: "UZS",
    value: "UZS",
    numericcode: "860",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "AZERBAIJAN",
    currency: "Azerbaijan Manat",
    label: "AYM",
    value: "AYM",
    numericcode: "945",
    minorunit: null,
    withdrawaldate: "2005-10",
  },
  {
    entity: "BELARUS",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-06",
  },
  {
    entity: "BOLIVIA",
    currency: "Peso boliviano",
    label: "BOP",
    value: "BOP",
    numericcode: "068",
    minorunit: null,
    withdrawaldate: "1987-02",
  },
  {
    entity: "BULGARIA",
    currency: "Lev A/52",
    label: "BGJ",
    value: "BGJ",
    numericcode: "100",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "GUADELOUPE",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "SLOVAKIA",
    currency: "Slovak Koruna",
    label: "SKK",
    value: "SKK",
    numericcode: "703",
    minorunit: null,
    withdrawaldate: "2009-01",
  },
  {
    entity: "AFGHANISTAN",
    currency: "Afghani",
    label: "AFN",
    value: "AFN",
    numericcode: "971",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "COMOROS (THE)",
    currency: "Comorian Franc",
    label: "KMF",
    value: "KMF",
    numericcode: "174",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "GAMBIA (THE)",
    currency: "Dalasi",
    label: "GMD",
    value: "GMD",
    numericcode: "270",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "IRAN (ISLAMIC REPUBLIC OF)",
    currency: "Iranian Rial",
    label: "IRR",
    value: "IRR",
    numericcode: "364",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ISRAEL",
    currency: "New Israeli Sheqel",
    label: "ILS",
    value: "ILS",
    numericcode: "376",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "KYRGYZSTAN",
    currency: "Som",
    label: "KGS",
    value: "KGS",
    numericcode: "417",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NEPAL",
    currency: "Nepalese Rupee",
    label: "NPR",
    value: "NPR",
    numericcode: "524",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAUDI ARABIA",
    currency: "Saudi Riyal",
    label: "SAR",
    value: "SAR",
    numericcode: "682",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency: "Bol\u00edvar Soberano",
    label: "VES",
    value: "VES",
    numericcode: "928",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ07_No_Currency",
    currency:
      "The codes assigned for transactions where no currency is involved",
    label: "XXX",
    value: "XXX",
    numericcode: "999",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "ANDORRA",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "CROATIA",
    currency: "Croatian Dinar",
    label: "HRD",
    value: "HRD",
    numericcode: "191",
    minorunit: null,
    withdrawaldate: "1995-01",
  },
  {
    entity: "MAYOTTE",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "ROMANIA",
    currency: "Leu A/52",
    label: "ROK",
    value: "ROK",
    numericcode: "642",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "ALBANIA",
    currency: "Lek",
    label: "ALL",
    value: "ALL",
    numericcode: "008",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "AMERICAN SAMOA",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ANTIGUA AND BARBUDA",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CHRISTMAS ISLAND",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GRENADA",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GUINEA",
    currency: "Guinean Franc",
    label: "GNF",
    value: "GNF",
    numericcode: "324",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "JORDAN",
    currency: "Jordanian Dinar",
    label: "JOD",
    value: "JOD",
    numericcode: "400",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "LESOTHO",
    currency: "Rand",
    label: "ZAR",
    value: "ZAR",
    numericcode: "710",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MALAWI",
    currency: "Malawi Kwacha",
    label: "MWK",
    value: "MWK",
    numericcode: "454",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SLOVAKIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SWEDEN",
    currency: "Swedish Krona",
    label: "SEK",
    value: "SEK",
    numericcode: "752",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TUVALU",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ09_Palladium",
    currency: "Palladium",
    label: "XPD",
    value: "XPD",
    numericcode: "964",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "BRAZIL",
    currency: "Cruzeiro",
    label: "BRE",
    value: "BRE",
    numericcode: "076",
    minorunit: null,
    withdrawaldate: "1993-03",
  },
  {
    entity: "ECUADOR",
    currency: "Unidad de Valor Constante (UVC)",
    label: "ECV",
    value: "ECV",
    numericcode: "983",
    minorunit: null,
    withdrawaldate: "2000-09",
  },
  {
    entity: "R\u00c9UNION",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "SAO TOME AND PRINCIPE",
    currency: "Dobra",
    label: "STD",
    value: "STD",
    numericcode: "678",
    minorunit: null,
    withdrawaldate: "2017-12",
  },
  {
    entity: "TURKMENISTAN",
    currency: "Turkmenistan Manat",
    label: "TMM",
    value: "TMM",
    numericcode: "795",
    minorunit: null,
    withdrawaldate: "2009-01",
  },
  {
    entity: "BOUVET ISLAND",
    currency: "Norwegian Krone",
    label: "NOK",
    value: "NOK",
    numericcode: "578",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "C\u00d4TE D'IVOIRE",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "CUBA",
    currency: "Cuban Peso",
    label: "CUP",
    value: "CUP",
    numericcode: "192",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GERMANY",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MOROCCO",
    currency: "Moroccan Dirham",
    label: "MAD",
    value: "MAD",
    numericcode: "504",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NIGERIA",
    currency: "Naira",
    label: "NGN",
    value: "NGN",
    numericcode: "566",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "AFGHANISTAN",
    currency: "Afghani",
    label: "AFA",
    value: "AFA",
    numericcode: "004",
    minorunit: null,
    withdrawaldate: "2003-01",
  },
  {
    entity: "ECUADOR",
    currency: "Sucre",
    label: "ECS",
    value: "ECS",
    numericcode: "218",
    minorunit: null,
    withdrawaldate: "2000-09",
  },
  {
    entity: "FINLAND",
    currency: "Markka",
    label: "FIM",
    value: "FIM",
    numericcode: "246",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "PERU",
    currency: "Sol",
    label: "PES",
    value: "PES",
    numericcode: "604",
    minorunit: null,
    withdrawaldate: "1986-02",
  },
  {
    entity: "SAINT-BARTH\u00c9LEMY",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "1999-01",
  },
  {
    entity: "COLOMBIA",
    currency: "Unidad de Valor Real",
    label: "COU",
    value: "COU",
    numericcode: "970",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GUADELOUPE",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "HOLY SEE (THE)",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "KUWAIT",
    currency: "Kuwaiti Dinar",
    label: "KWD",
    value: "KWD",
    numericcode: "414",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "LEBANON",
    currency: "Lebanese Pound",
    label: "LBP",
    value: "LBP",
    numericcode: "422",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT BARTH\u00c9LEMY",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "AUSTRIA",
    currency: "Schilling",
    label: "ATS",
    value: "ATS",
    numericcode: "040",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "AZERBAIJAN",
    currency: "Russian Ruble",
    label: "RUR",
    value: "RUR",
    numericcode: "810",
    minorunit: null,
    withdrawaldate: "1994-08",
  },
  {
    entity: "BELARUS",
    currency: "Belarusian Ruble",
    label: "BYB",
    value: "BYB",
    numericcode: "112",
    minorunit: null,
    withdrawaldate: "2001-01",
  },
  {
    entity: "MALAWI",
    currency: "Kwacha",
    label: "MWK",
    value: "MWK",
    numericcode: "454",
    minorunit: null,
    withdrawaldate: "2016-02",
  },
  {
    entity: "ZIMBABWE",
    currency: "Zimbabwe Dollar",
    label: "ZWD",
    value: "ZWD",
    numericcode: "716",
    minorunit: null,
    withdrawaldate: "2008-08",
  },
  {
    entity: "ARMENIA",
    currency: "Armenian Dram",
    label: "AMD",
    value: "AMD",
    numericcode: "051",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BELGIUM",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GIBRALTAR",
    currency: "Gibraltar Pound",
    label: "GIP",
    value: "GIP",
    numericcode: "292",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NORTH MACEDONIA",
    currency: "Denar",
    label: "MKD",
    value: "MKD",
    numericcode: "807",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MALAYSIA",
    currency: "Malaysian Ringgit",
    label: "MYR",
    value: "MYR",
    numericcode: "458",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MEXICO",
    currency: "Mexican Peso",
    label: "MXN",
    value: "MXN",
    numericcode: "484",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MICRONESIA (FEDERATED STATES OF)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NIGER (THE)",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "RUSSIAN FEDERATION (THE)",
    currency: "Russian Ruble",
    label: "RUB",
    value: "RUB",
    numericcode: "643",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SOUTH AFRICA",
    currency: "Rand",
    label: "ZAR",
    value: "ZAR",
    numericcode: "710",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SWITZERLAND",
    currency: "Swiss Franc",
    label: "CHF",
    value: "CHF",
    numericcode: "756",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "THAILAND",
    currency: "Baht",
    label: "THB",
    value: "THB",
    numericcode: "764",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TOGO",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "TONGA",
    currency: "Pa'anga",
    label: "TOP",
    value: "TOP",
    numericcode: "776",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TURKMENISTAN",
    currency: "Turkmenistan New Manat",
    label: "TMT",
    value: "TMT",
    numericcode: "934",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ARGENTINA",
    currency: "Peso",
    label: "ARY",
    value: "ARY",
    numericcode: "032",
    minorunit: null,
    withdrawaldate: "1989 to 1990",
  },
  {
    entity: "EUROPEAN MONETARY CO-OPERATION FUND (EMCF)",
    currency: "European Currency Unit (E.C.U)",
    label: "XEU",
    value: "XEU",
    numericcode: "954",
    minorunit: null,
    withdrawaldate: "1999-01",
  },
  {
    entity: "ITALY",
    currency: "Italian Lira",
    label: "ITL",
    value: "ITL",
    numericcode: "380",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "ARGENTINA",
    currency: "Argentine Peso",
    label: "ARS",
    value: "ARS",
    numericcode: "032",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ETHIOPIA",
    currency: "Ethiopian Birr",
    label: "ETB",
    value: "ETB",
    numericcode: "230",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FRENCH GUIANA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "INTERNATIONAL MONETARY FUND (IMF)",
    currency: "SDR (Special Drawing Right)",
    label: "XDR",
    value: "XDR",
    numericcode: "960",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "IRAQ",
    currency: "Iraqi Dinar",
    label: "IQD",
    value: "IQD",
    numericcode: "368",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "KIRIBATI",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MALI",
    currency: "CFA Franc BCEAO",
    label: "XOF",
    value: "XOF",
    numericcode: "952",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
    currency: "ADB Unit of Account",
    label: "XUA",
    value: "XUA",
    numericcode: "965",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "MONTSERRAT",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "NAMIBIA",
    currency: "Namibia Dollar",
    label: "NAD",
    value: "NAD",
    numericcode: "516",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PAKISTAN",
    currency: "Pakistan Rupee",
    label: "PKR",
    value: "PKR",
    numericcode: "586",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT VINCENT AND THE GRENADINES",
    currency: "East Caribbean Dollar",
    label: "XCD",
    value: "XCD",
    numericcode: "951",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "TAJIKISTAN",
    currency: "Somoni",
    label: "TJS",
    value: "TJS",
    numericcode: "972",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "YEMEN",
    currency: "Yemeni Rial",
    label: "YER",
    value: "YER",
    numericcode: "886",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZIMBABWE",
    currency: "Zimbabwe Dollar",
    label: "ZWL",
    value: "ZWL",
    numericcode: "932",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ANGOLA",
    currency: "Kwanza",
    label: "AOK",
    value: "AOK",
    numericcode: "024",
    minorunit: null,
    withdrawaldate: "1991-03",
  },
  {
    entity: "SOUTHERN RHODESIA",
    currency: "Rhodesian Dollar",
    label: "RHD",
    value: "RHD",
    numericcode: "716",
    minorunit: null,
    withdrawaldate: "1978 to 1981",
  },
  {
    entity: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency: "Bolivar",
    label: "VEF",
    value: "VEF",
    numericcode: "937",
    minorunit: null,
    withdrawaldate: "2016-02",
  },
  {
    entity: "YUGOSLAVIA",
    currency: "New Dinar",
    label: "YUM",
    value: "YUM",
    numericcode: "891",
    minorunit: null,
    withdrawaldate: "2003-07",
  },
  {
    entity: "BRUNEI DARUSSALAM",
    currency: "Brunei Dollar",
    label: "BND",
    value: "BND",
    numericcode: "096",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FRANCE",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "GHANA",
    currency: "Ghana Cedi",
    label: "GHS",
    value: "GHS",
    numericcode: "936",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LATVIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LIECHTENSTEIN",
    currency: "Swiss Franc",
    label: "CHF",
    value: "CHF",
    numericcode: "756",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SOMALIA",
    currency: "Somali Shilling",
    label: "SOS",
    value: "SOS",
    numericcode: "706",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SUDAN (THE)",
    currency: "Sudanese Pound",
    label: "SDG",
    value: "SDG",
    numericcode: "938",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "WESTERN SAHARA",
    currency: "Moroccan Dirham",
    label: "MAD",
    value: "MAD",
    numericcode: "504",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MARTINIQUE",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "SAINT MARTIN",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "1999-01",
  },
  {
    entity: "SAN MARINO",
    currency: "Italian Lira",
    label: "ITL",
    value: "ITL",
    numericcode: "380",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "ZIMBABWE",
    currency: "Zimbabwe Dollar (old)",
    label: "ZWD",
    value: "ZWD",
    numericcode: "716",
    minorunit: null,
    withdrawaldate: "2006-08",
  },
  {
    entity: "ZIMBABWE",
    currency: "Zimbabwe Dollar",
    label: "ZWR",
    value: "ZWR",
    numericcode: "935",
    minorunit: null,
    withdrawaldate: "2009-06",
  },
  {
    entity: "BHUTAN",
    currency: "Indian Rupee",
    label: "INR",
    value: "INR",
    numericcode: "356",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BOSNIA AND HERZEGOVINA",
    currency: "Convertible Mark",
    label: "BAM",
    value: "BAM",
    numericcode: "977",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "COLOMBIA",
    currency: "Colombian Peso",
    label: "COP",
    value: "COP",
    numericcode: "170",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CROATIA",
    currency: "Kuna",
    label: "HRK",
    value: "HRK",
    numericcode: "191",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ESTONIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "HUNGARY",
    currency: "Forint",
    label: "HUF",
    value: "HUF",
    numericcode: "348",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "JAMAICA",
    currency: "Jamaican Dollar",
    label: "JMD",
    value: "JMD",
    numericcode: "388",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "LIBYA",
    currency: "Libyan Dinar",
    label: "LYD",
    value: "LYD",
    numericcode: "434",
    minorunit: "3",
    withdrawaldate: null,
  },
  {
    entity: "NAURU",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "UNITED STATES OF AMERICA (THE)",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ZZ03_Bond Markets Unit European_EUA-9",
    currency: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    label: "XBC",
    value: "XBC",
    numericcode: "957",
    minorunit: "-",
    withdrawaldate: null,
  },
  {
    entity: "MALI",
    currency: "Mali Franc",
    label: "MLF",
    value: "MLF",
    numericcode: "466",
    minorunit: null,
    withdrawaldate: "1984-11",
  },
  {
    entity: "SUDAN",
    currency: "Sudanese Dinar",
    label: "SDD",
    value: "SDD",
    numericcode: "736",
    minorunit: null,
    withdrawaldate: "2007-07",
  },
  {
    entity: "ZIMBABWE",
    currency: "Rhodesian Dollar",
    label: "ZWC",
    value: "ZWC",
    numericcode: "716",
    minorunit: null,
    withdrawaldate: "1989-12",
  },
  {
    entity: "BANGLADESH",
    currency: "Taka",
    label: "BDT",
    value: "BDT",
    numericcode: "050",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "BRAZIL",
    currency: "Brazilian Real",
    label: "BRL",
    value: "BRL",
    numericcode: "986",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "FIJI",
    currency: "Fiji Dollar",
    label: "FJD",
    value: "FJD",
    numericcode: "242",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "HONDURAS",
    currency: "Lempira",
    label: "HNL",
    value: "HNL",
    numericcode: "340",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MAURITANIA",
    currency: "Ouguiya",
    label: "MRU",
    value: "MRU",
    numericcode: "929",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MONACO",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PALAU",
    currency: "US Dollar",
    label: "USD",
    value: "USD",
    numericcode: "840",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "PARAGUAY",
    currency: "Guarani",
    label: "PYG",
    value: "PYG",
    numericcode: "600",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "SEYCHELLES",
    currency: "Seychelles Rupee",
    label: "SCR",
    value: "SCR",
    numericcode: "690",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ANGOLA",
    currency: "Kwanza Reajustado",
    label: "AOR",
    value: "AOR",
    numericcode: "982",
    minorunit: null,
    withdrawaldate: "2000-02",
  },
  {
    entity: "AZERBAIJAN",
    currency: "Azerbaijanian Manat",
    label: "AZM",
    value: "AZM",
    numericcode: "031",
    minorunit: null,
    withdrawaldate: "2005-12",
  },
  {
    entity: "GUINEA",
    currency: "Syli",
    label: "GNE",
    value: "GNE",
    numericcode: "324",
    minorunit: null,
    withdrawaldate: "1989-12",
  },
  {
    entity: "ISRAEL",
    currency: "Pound",
    label: "ILP",
    value: "ILP",
    numericcode: "376",
    minorunit: null,
    withdrawaldate: "1978 to 1981",
  },
  {
    entity: "MADAGASCAR",
    currency: "Malagasy Franc",
    label: "MGF",
    value: "MGF",
    numericcode: "450",
    minorunit: null,
    withdrawaldate: "2004-12",
  },
  {
    entity: "SAINT PIERRE AND MIQUELON",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "SPAIN",
    currency: '"A" Account (convertible Peseta Account)',
    label: "ESB",
    value: "ESB",
    numericcode: "995",
    minorunit: null,
    withdrawaldate: "1994-12",
  },
  {
    entity: "SWAZILAND",
    currency: "Lilangeni",
    label: "SZL",
    value: "SZL",
    numericcode: "748",
    minorunit: null,
    withdrawaldate: "2018-08",
  },
  {
    entity: "TAJIKISTAN",
    currency: "Tajik Ruble",
    label: "TJR",
    value: "TJR",
    numericcode: "762",
    minorunit: null,
    withdrawaldate: "2001-04",
  },
  {
    entity: "AUSTRALIA",
    currency: "Australian Dollar",
    label: "AUD",
    value: "AUD",
    numericcode: "036",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "CURA\u00c7AO",
    currency: "Netherlands Antillean Guilder",
    label: "ANG",
    value: "ANG",
    numericcode: "532",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "EGYPT",
    currency: "Egyptian Pound",
    label: "EGP",
    value: "EGP",
    numericcode: "818",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ESWATINI",
    currency: "Lilangeni",
    label: "SZL",
    value: "SZL",
    numericcode: "748",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ISLE OF MAN",
    currency: "Pound Sterling",
    label: "GBP",
    value: "GBP",
    numericcode: "826",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "JAPAN",
    currency: "Yen",
    label: "JPY",
    value: "JPY",
    numericcode: "392",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "JERSEY",
    currency: "Pound Sterling",
    label: "GBP",
    value: "GBP",
    numericcode: "826",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MACAO",
    currency: "Pataca",
    label: "MOP",
    value: "MOP",
    numericcode: "446",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "MYANMAR",
    currency: "Kyat",
    label: "MMK",
    value: "MMK",
    numericcode: "104",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "ROMANIA",
    currency: "Romanian Leu",
    label: "RON",
    value: "RON",
    numericcode: "946",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SAINT MARTIN (FRENCH PART)",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "SLOVENIA",
    currency: "Euro",
    label: "EUR",
    value: "EUR",
    numericcode: "978",
    minorunit: "2",
    withdrawaldate: null,
  },
  {
    entity: "VIET NAM",
    currency: "Dong",
    label: "VND",
    value: "VND",
    numericcode: "704",
    minorunit: "0",
    withdrawaldate: null,
  },
  {
    entity: "ANGOLA",
    currency: "New Kwanza",
    label: "AON",
    value: "AON",
    numericcode: "024",
    minorunit: null,
    withdrawaldate: "2000-02",
  },
  {
    entity: "MALTA",
    currency: "Maltese Lira",
    label: "MTL",
    value: "MTL",
    numericcode: "470",
    minorunit: null,
    withdrawaldate: "2008-01",
  },
  {
    entity: "MAURITANIA",
    currency: "Ouguiya",
    label: "MRO",
    value: "MRO",
    numericcode: "478",
    minorunit: null,
    withdrawaldate: "2017-12",
  },
  {
    entity: "MONACO",
    currency: "French Franc",
    label: "FRF",
    value: "FRF",
    numericcode: "250",
    minorunit: null,
    withdrawaldate: "2002-03",
  },
  {
    entity: "MOZAMBIQUE",
    currency: "Mozambique Escudo",
    label: "MZE",
    value: "MZE",
    numericcode: "508",
    minorunit: null,
    withdrawaldate: "1978 to 1981",
  },
  {
    entity: "SURINAME",
    currency: "Surinam Guilder",
    label: "SRG",
    value: "SRG",
    numericcode: "740",
    minorunit: null,
    withdrawaldate: "2003-12",
  },
  {
    entity: "TURKEY",
    currency: "New Turkish Lira",
    label: "TRY",
    value: "TRY",
    numericcode: "949",
    minorunit: null,
    withdrawaldate: "2009-01",
  },
  {
    entity: "YEMEN, DEMOCRATIC",
    currency: "Yemeni Dinar",
    label: "YDD",
    value: "YDD",
    numericcode: "720",
    minorunit: null,
    withdrawaldate: "1991-09",
  },
];
